/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Node API Server Documentation
 * API documentation for Node API Server. Generated automatically from source code comments.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import { customInstance } from '../axios/index';
export interface User {
  /** 用户ID */
  id: number;
  /** 用户名 */
  username: string;
  /** 真实姓名 */
  name: string;
}

export interface Role {
  /** 角色ID */
  id: number;
  /** 角色名称 */
  name: string;
  /** 角色描述 */
  description?: string;
}

export interface Product {
  /** 商品ID */
  id: number;
  /** 商品名称 */
  name: string;
  /** 价格 */
  price: number;
  /** 库存数量 */
  stock: number;
  /** 状态 (active/inactive) */
  status: string;
}

/**
 * 菜单类型 (0:目录, 1:菜单, 2:按钮)
 */
export type MenuItemType = typeof MenuItemType[keyof typeof MenuItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MenuItemType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export interface MenuItem {
  /** 菜单 ID */
  id: number;
  /**
   * 父级菜单 ID
   * @nullable
   */
  parentId?: number | null;
  /** 路由路径 */
  path: string;
  /** 路由名称 (PascalCase) */
  name: string;
  /** 组件路径 (Layout/ParentView/views路径) */
  component: string;
  /** 路由重定向 */
  redirect?: string;
  /** 菜单标题 */
  title: string;
  /** 菜单图标 (Element Plus 图标名) */
  icon?: string;
  /** 是否需要登录授权 */
  requiresAuth?: boolean;
  /** 是否隐藏面包屑 */
  hideBreadcrumb?: boolean;
  /** 是否启用 */
  enabled?: boolean;
  /** 是否隐藏 */
  hidden?: boolean;
  /** 高亮菜单项的路径 */
  activeMenu?: string;
  /** 是否开启缓存 */
  keepAlive?: boolean;
  /** 权限标识数组 */
  permissions?: string[];
  /** 菜单类型 (0:目录, 1:菜单, 2:按钮) */
  type?: MenuItemType;
  /** 排序号 */
  sort?: number;
  /** 是否固定在 TagsView */
  affix?: boolean;
  /** 是否全屏显示 */
  fullScreen?: boolean;
  /** 总是显示根菜单 */
  alwaysShow?: boolean;
  /** 外部链接 */
  externalLink?: string;
  /** 内嵌 Iframe 地址 */
  frameSrc?: string;
  /** 子菜单列表 */
  children?: MenuItem[];
}

/**
 * @nullable
 */
export type ErrorData = { [key: string]: unknown } | null;

export interface Error {
  code: number;
  /** 错误信息描述 */
  message: string;
  /** @nullable */
  data: ErrorData;
}

export type LoginBody = {
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
};

export type Login200Data = {
  /** JWT访问令牌，用于后续请求认证 */
  accessToken: string;
  user: User;
};

export type Login200 = {
  code: number;
  message: string;
  data: Login200Data;
};

export type Refresh200Data = {
  /** 新的JWT访问令牌 */
  accessToken: string;
};

export type Refresh200 = {
  code: number;
  message: string;
  data: Refresh200Data;
};

/**
 * @nullable
 */
export type Logout200Data = { [key: string]: unknown } | null;

export type Logout200 = {
  code: number;
  message: string;
  /** @nullable */
  data: Logout200Data;
};

export type GetProfile200DataAllOf = {
  roles: Role[];
};

export type GetProfile200Data = User & GetProfile200DataAllOf;

export type GetProfile200 = {
  code: number;
  message: string;
  data: GetProfile200Data;
};

export type GetMenus200 = {
  code: number;
  message: string;
  /** 菜单树结构 */
  data: MenuItem[];
};

export type GetPermissions200 = {
  code: number;
  message: string;
  data: string[];
};

export type GetAllUsers200 = {
  code: number;
  message: string;
  data: User[];
};

export type CreateUserBody = {
  /** 用户名 */
  username: string;
  /** 初始密码 */
  password: string;
  /** 真实姓名 */
  name?: string;
};

export type CreateUser201 = {
  code: number;
  message: string;
  data: User;
};

export type GetUserById200 = {
  code: number;
  message: string;
  data: User;
};

export type UpdateUserBody = {
  /** 真实姓名 */
  name?: string;
  /** 是否启用 */
  enabled?: boolean;
};

export type UpdateUser200 = {
  code: number;
  message: string;
  data: User;
};

/**
 * @nullable
 */
export type DeleteUser200Data = { [key: string]: unknown } | null;

export type DeleteUser200 = {
  code: number;
  message: string;
  /** @nullable */
  data: DeleteUser200Data;
};

export type UpdateUserRolesBody = {
  /** 角色ID数组 */
  roleIds: number[];
};

/**
 * @nullable
 */
export type UpdateUserRoles200Data = { [key: string]: unknown } | null;

export type UpdateUserRoles200 = {
  code: number;
  message: string;
  /** @nullable */
  data: UpdateUserRoles200Data;
};

export type GetAllRoles200 = {
  code: number;
  message: string;
  data: Role[];
};

export type CreateRoleBody = {
  /** 角色名称 */
  name: string;
  /** 角色描述 */
  description?: string;
};

export type CreateRole201 = {
  code: number;
  message: string;
  data: Role;
};

export type GetRoleById200 = {
  code: number;
  message: string;
  data: Role;
};

export type UpdateRoleBody = {
  /** 角色名称 */
  name: string;
  /** 角色描述 */
  description?: string;
};

export type UpdateRole200 = {
  code: number;
  message: string;
  data: Role;
};

/**
 * @nullable
 */
export type DeleteRole200Data = { [key: string]: unknown } | null;

export type DeleteRole200 = {
  code: number;
  message: string;
  /** @nullable */
  data: DeleteRole200Data;
};

export type UpdateRolePermissionsBody = {
  /** 权限ID数组 */
  permissionIds: number[];
};

/**
 * @nullable
 */
export type UpdateRolePermissions200Data = { [key: string]: unknown } | null;

export type UpdateRolePermissions200 = {
  code: number;
  message: string;
  /** @nullable */
  data: UpdateRolePermissions200Data;
};

export type UpdateRoleMenusBody = {
  /** 菜单ID数组 */
  menuIds: number[];
};

/**
 * @nullable
 */
export type UpdateRoleMenus200Data = { [key: string]: unknown } | null;

export type UpdateRoleMenus200 = {
  code: number;
  message: string;
  /** @nullable */
  data: UpdateRoleMenus200Data;
};

export type GetAllMenus200 = {
  code: number;
  message: string;
  data: MenuItem[];
};

export type CreateMenuBody = {
  /** 菜单标题 */
  title: string;
  /** 菜单路径 */
  path: string;
  /** 菜单名称 */
  name: string;
  /** 组件路径 */
  component?: string;
  /** 菜单图标 */
  icon?: string;
  /** 排序序号 */
  sort?: number;
  /** 父菜单ID（如果是子菜单） */
  parentId?: number;
};

export type CreateMenu201 = {
  code: number;
  message: string;
  data: MenuItem;
};

export type GetMenuById200 = {
  code: number;
  message: string;
  data: MenuItem;
};

export type UpdateMenuBody = {
  /** 菜单标题 */
  title?: string;
  /** 菜单路径 */
  path?: string;
  /** 菜单图标 */
  icon?: string;
  /** 排序序号 */
  sort?: number;
};

export type UpdateMenu200 = {
  code: number;
  message: string;
  data: MenuItem;
};

/**
 * @nullable
 */
export type DeleteMenu200Data = { [key: string]: unknown } | null;

export type DeleteMenu200 = {
  code: number;
  message: string;
  /** @nullable */
  data: DeleteMenu200Data;
};

export type GetAllProducts200 = {
  code: number;
  message: string;
  data: Product[];
};

export type CreateProduct201 = {
  code: number;
  message: string;
  data: Product;
};

export type GetProductById200 = {
  code: number;
  message: string;
  data: Product;
};

export type UpdateProduct200 = {
  code: number;
  message: string;
  data: Product;
};

/**
 * @nullable
 */
export type DeleteProduct200Data = { [key: string]: unknown } | null;

export type DeleteProduct200 = {
  code: number;
  message: string;
  /** @nullable */
  data: DeleteProduct200Data;
};

/**
 * 变更前的数据快照 (Optional)
 */
export type TriggerPermissionChangeBodyBefore = { [key: string]: unknown };

/**
 * 变更后的数据快照 (Optional)
 */
export type TriggerPermissionChangeBodyAfter = { [key: string]: unknown };

export type TriggerPermissionChangeBody = {
  /** 目标用户ID (Required) - 权限发生变更的用户 */
  userId: number;
  /** 变更类型标识符 (Required) - 如 'user_role_update' */
  type: string;
  /** 变更前的数据快照 (Optional) */
  before?: TriggerPermissionChangeBodyBefore;
  /** 变更后的数据快照 (Optional) */
  after?: TriggerPermissionChangeBodyAfter;
};

/**
 * 发送给客户端的事件负载
 */
export type TriggerPermissionChange200DataPayload = {
  userId: number;
  type: string;
};

export type TriggerPermissionChange200Data = {
  triggered: boolean;
  /** 发送给客户端的事件负载 */
  payload: TriggerPermissionChange200DataPayload;
};

export type TriggerPermissionChange200 = {
  code: number;
  message: string;
  data: TriggerPermissionChange200Data;
};

/**
 * 用户通过用户名和密码进行登录，获取访问令牌(Access Token)和用户信息。刷新令牌(Refresh Token)将通过HttpOnly Cookie设置。
 * @summary 用户登录
 */
export const login = (
    loginBody: MaybeRef<LoginBody>,
 signal?: AbortSignal
) => {
      loginBody = unref(loginBody);
      
      return customInstance<Login200>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginBody, signal
    },
      );
    }
  


export const getLoginMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginBody}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: LoginBody}> = (props) => {
          const {data} = props ?? {};

          return  login(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginBody
    export type LoginMutationError = Error

    /**
 * @summary 用户登录
 */
export const useLogin = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: LoginBody},
        TContext
      > => {

      const mutationOptions = getLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 使用Cookie中的Refresh Token换取新的Access Token。用于前端Access Token过期后的无感刷新。
 * @summary 刷新令牌
 */
export const refresh = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<Refresh200>(
      {url: `/auth/refresh`, method: 'POST', signal
    },
      );
    }
  


export const getRefreshMutationOptions = <TError = Error | Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,void, TContext> => {

const mutationKey = ['refresh'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refresh>>, void> = () => {
          

          return  refresh()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RefreshMutationResult = NonNullable<Awaited<ReturnType<typeof refresh>>>
    
    export type RefreshMutationError = Error | Error

    /**
 * @summary 刷新令牌
 */
export const useRefresh = <TError = Error | Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof refresh>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getRefreshMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 清除服务端的Refresh Token记录（如果有），并通知客户端清除Cookie。
 * @summary 用户登出
 */
export const logout = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<Logout200>(
      {url: `/auth/logout`, method: 'POST', signal
    },
      );
    }
  


export const getLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {
          

          return  logout()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>
    
    export type LogoutMutationError = unknown

    /**
 * @summary 用户登出
 */
export const useLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof logout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 获取当前登录用户的详细信息，包含角色列表。需要有效的Access Token。
 * @summary 获取个人资料
 */
export const getProfile = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetProfile200>(
      {url: `/user/profile`, method: 'GET', signal
    },
      );
    }
  



export const getGetProfileQueryKey = () => {
    return [
    'user','profile'
    ] as const;
    }

    
export const getGetProfileQueryOptions = <TData = Awaited<ReturnType<typeof getProfile>>, TError = Error>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  getGetProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProfile>>> = ({ signal }) => getProfile(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData> 
}

export type GetProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getProfile>>>
export type GetProfileQueryError = Error


/**
 * @summary 获取个人资料
 */

export function useGetProfile<TData = Awaited<ReturnType<typeof getProfile>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * 根据用户角色的权限，获取动态菜单 tree 结构。用于前端生成左侧菜单栏。
 * @summary 获取用户菜单
 */
export const getMenus = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetMenus200>(
      {url: `/user/menus`, method: 'GET', signal
    },
      );
    }
  



export const getGetMenusQueryKey = () => {
    return [
    'user','menus'
    ] as const;
    }

    
export const getGetMenusQueryOptions = <TData = Awaited<ReturnType<typeof getMenus>>, TError = Error>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMenus>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  getGetMenusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMenus>>> = ({ signal }) => getMenus(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMenus>>, TError, TData> 
}

export type GetMenusQueryResult = NonNullable<Awaited<ReturnType<typeof getMenus>>>
export type GetMenusQueryError = Error


/**
 * @summary 获取用户菜单
 */

export function useGetMenus<TData = Awaited<ReturnType<typeof getMenus>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMenus>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMenusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * 获取当前用户拥有的所有权限标识符列表（如 'user:view', 'role:edit'）。用于前端按钮级别的权限控制。
 * @summary 获取用户权限码
 */
export const getPermissions = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetPermissions200>(
      {url: `/user/permissions`, method: 'GET', signal
    },
      );
    }
  



export const getGetPermissionsQueryKey = () => {
    return [
    'user','permissions'
    ] as const;
    }

    
export const getGetPermissionsQueryOptions = <TData = Awaited<ReturnType<typeof getPermissions>>, TError = Error>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPermissions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  getGetPermissionsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPermissions>>> = ({ signal }) => getPermissions(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPermissions>>, TError, TData> 
}

export type GetPermissionsQueryResult = NonNullable<Awaited<ReturnType<typeof getPermissions>>>
export type GetPermissionsQueryError = Error


/**
 * @summary 获取用户权限码
 */

export function useGetPermissions<TData = Awaited<ReturnType<typeof getPermissions>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPermissions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPermissionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * 获取系统中所有用户的列表。需要 'user:view' 权限。
 * @summary 获取用户列表
 */
export const getAllUsers = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetAllUsers200>(
      {url: `/users`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllUsersQueryKey = () => {
    return [
    'users'
    ] as const;
    }

    
export const getGetAllUsersQueryOptions = <TData = Awaited<ReturnType<typeof getAllUsers>>, TError = Error>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  getGetAllUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUsers>>> = ({ signal }) => getAllUsers(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData> 
}

export type GetAllUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllUsers>>>
export type GetAllUsersQueryError = Error


/**
 * @summary 获取用户列表
 */

export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * 创建一个新的系统用户。需要 'user:add' 权限。
 * @summary 创建新用户
 */
export const createUser = (
    createUserBody: MaybeRef<CreateUserBody>,
 signal?: AbortSignal
) => {
      createUserBody = unref(createUserBody);
      
      return customInstance<CreateUser201>(
      {url: `/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserBody, signal
    },
      );
    }
  


export const getCreateUserMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: CreateUserBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: CreateUserBody}, TContext> => {

const mutationKey = ['createUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUser>>, {data: CreateUserBody}> = (props) => {
          const {data} = props ?? {};

          return  createUser(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof createUser>>>
    export type CreateUserMutationBody = CreateUserBody
    export type CreateUserMutationError = Error

    /**
 * @summary 创建新用户
 */
export const useCreateUser = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: CreateUserBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createUser>>,
        TError,
        {data: CreateUserBody},
        TContext
      > => {

      const mutationOptions = getCreateUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 根据ID获取特定用户的详细信息。需要 'user:view' 权限。
 * @summary 获取用户详情
 */
export const getUserById = (
    id: MaybeRef<number>,
 signal?: AbortSignal
) => {
      id = unref(id);
      
      return customInstance<GetUserById200>(
      {url: `/users/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetUserByIdQueryKey = (id?: MaybeRef<number>,) => {
    return [
    'users',id
    ] as const;
    }

    
export const getGetUserByIdQueryOptions = <TData = Awaited<ReturnType<typeof getUserById>>, TError = Error>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  getGetUserByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserById>>> = ({ signal }) => getUserById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData> 
}

export type GetUserByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUserById>>>
export type GetUserByIdQueryError = Error


/**
 * @summary 获取用户详情
 */

export function useGetUserById<TData = Awaited<ReturnType<typeof getUserById>>, TError = Error>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * 更新现有用户的基本信息。需要 'user:edit' 权限。
 * @summary 更新用户信息
 */
export const updateUser = (
    id: MaybeRef<number>,
    updateUserBody: MaybeRef<UpdateUserBody>,
 ) => {
      id = unref(id);
updateUserBody = unref(updateUserBody);
      
      return customInstance<UpdateUser200>(
      {url: `/users/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateUserBody
    },
      );
    }
  


export const getUpdateUserMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: UpdateUserBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: UpdateUserBody}, TContext> => {

const mutationKey = ['updateUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUser>>, {id: number;data: UpdateUserBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateUser(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
    export type UpdateUserMutationBody = UpdateUserBody
    export type UpdateUserMutationError = Error

    /**
 * @summary 更新用户信息
 */
export const useUpdateUser = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{id: number;data: UpdateUserBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateUser>>,
        TError,
        {id: number;data: UpdateUserBody},
        TContext
      > => {

      const mutationOptions = getUpdateUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 删除指定ID的用户。需要 'user:delete' 权限。
 * @summary 删除用户
 */
export const deleteUser = (
    id: MaybeRef<number>,
 ) => {
      id = unref(id);
      
      return customInstance<DeleteUser200>(
      {url: `/users/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteUserMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteUser(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
    
    export type DeleteUserMutationError = Error

    /**
 * @summary 删除用户
 */
export const useDeleteUser = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 更新指定用户的角色列表。需要 'user:edit' 权限。
 * @summary 分配用户角色
 */
export const updateUserRoles = (
    id: MaybeRef<number>,
    updateUserRolesBody: MaybeRef<UpdateUserRolesBody>,
 ) => {
      id = unref(id);
updateUserRolesBody = unref(updateUserRolesBody);
      
      return customInstance<UpdateUserRoles200>(
      {url: `/users/${id}/roles`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateUserRolesBody
    },
      );
    }
  


export const getUpdateUserRolesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserRoles>>, TError,{id: number;data: UpdateUserRolesBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateUserRoles>>, TError,{id: number;data: UpdateUserRolesBody}, TContext> => {

const mutationKey = ['updateUserRoles'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserRoles>>, {id: number;data: UpdateUserRolesBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateUserRoles(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserRolesMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserRoles>>>
    export type UpdateUserRolesMutationBody = UpdateUserRolesBody
    export type UpdateUserRolesMutationError = unknown

    /**
 * @summary 分配用户角色
 */
export const useUpdateUserRoles = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserRoles>>, TError,{id: number;data: UpdateUserRolesBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateUserRoles>>,
        TError,
        {id: number;data: UpdateUserRolesBody},
        TContext
      > => {

      const mutationOptions = getUpdateUserRolesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 获取系统中所有角色的列表。需要 'role:view' 权限。
 * @summary 获取角色列表
 */
export const getAllRoles = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetAllRoles200>(
      {url: `/roles`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllRolesQueryKey = () => {
    return [
    'roles'
    ] as const;
    }

    
export const getGetAllRolesQueryOptions = <TData = Awaited<ReturnType<typeof getAllRoles>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRoles>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  getGetAllRolesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllRoles>>> = ({ signal }) => getAllRoles(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllRoles>>, TError, TData> 
}

export type GetAllRolesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllRoles>>>
export type GetAllRolesQueryError = unknown


/**
 * @summary 获取角色列表
 */

export function useGetAllRoles<TData = Awaited<ReturnType<typeof getAllRoles>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllRoles>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllRolesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * 创建一个新的系统角色。
 * @summary 创建新角色
 */
export const createRole = (
    createRoleBody: MaybeRef<CreateRoleBody>,
 signal?: AbortSignal
) => {
      createRoleBody = unref(createRoleBody);
      
      return customInstance<CreateRole201>(
      {url: `/roles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRoleBody, signal
    },
      );
    }
  


export const getCreateRoleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRole>>, TError,{data: CreateRoleBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createRole>>, TError,{data: CreateRoleBody}, TContext> => {

const mutationKey = ['createRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRole>>, {data: CreateRoleBody}> = (props) => {
          const {data} = props ?? {};

          return  createRole(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRoleMutationResult = NonNullable<Awaited<ReturnType<typeof createRole>>>
    export type CreateRoleMutationBody = CreateRoleBody
    export type CreateRoleMutationError = unknown

    /**
 * @summary 创建新角色
 */
export const useCreateRole = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRole>>, TError,{data: CreateRoleBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createRole>>,
        TError,
        {data: CreateRoleBody},
        TContext
      > => {

      const mutationOptions = getCreateRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 获取特定角色的详细信息。需要 'role:view' 权限。
 * @summary 获取角色详情
 */
export const getRoleById = (
    id: MaybeRef<number>,
 signal?: AbortSignal
) => {
      id = unref(id);
      
      return customInstance<GetRoleById200>(
      {url: `/roles/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetRoleByIdQueryKey = (id?: MaybeRef<number>,) => {
    return [
    'roles',id
    ] as const;
    }

    
export const getGetRoleByIdQueryOptions = <TData = Awaited<ReturnType<typeof getRoleById>>, TError = Error>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoleById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  getGetRoleByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRoleById>>> = ({ signal }) => getRoleById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRoleById>>, TError, TData> 
}

export type GetRoleByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getRoleById>>>
export type GetRoleByIdQueryError = Error


/**
 * @summary 获取角色详情
 */

export function useGetRoleById<TData = Awaited<ReturnType<typeof getRoleById>>, TError = Error>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoleById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRoleByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * 更新现有角色的基本信息。
 * @summary 更新角色信息
 */
export const updateRole = (
    id: MaybeRef<number>,
    updateRoleBody: MaybeRef<UpdateRoleBody>,
 ) => {
      id = unref(id);
updateRoleBody = unref(updateRoleBody);
      
      return customInstance<UpdateRole200>(
      {url: `/roles/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateRoleBody
    },
      );
    }
  


export const getUpdateRoleMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRole>>, TError,{id: number;data: UpdateRoleBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateRole>>, TError,{id: number;data: UpdateRoleBody}, TContext> => {

const mutationKey = ['updateRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRole>>, {id: number;data: UpdateRoleBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateRole(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateRoleMutationResult = NonNullable<Awaited<ReturnType<typeof updateRole>>>
    export type UpdateRoleMutationBody = UpdateRoleBody
    export type UpdateRoleMutationError = Error

    /**
 * @summary 更新角色信息
 */
export const useUpdateRole = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRole>>, TError,{id: number;data: UpdateRoleBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateRole>>,
        TError,
        {id: number;data: UpdateRoleBody},
        TContext
      > => {

      const mutationOptions = getUpdateRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 删除指定角色。
 * @summary 删除角色
 */
export const deleteRole = (
    id: MaybeRef<number>,
 ) => {
      id = unref(id);
      
      return customInstance<DeleteRole200>(
      {url: `/roles/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteRoleMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRole>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteRole>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteRole'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRole>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteRole(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteRoleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRole>>>
    
    export type DeleteRoleMutationError = Error

    /**
 * @summary 删除角色
 */
export const useDeleteRole = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRole>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteRole>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 更新指定角色的权限列表。
 * @summary 分配角色权限
 */
export const updateRolePermissions = (
    id: MaybeRef<number>,
    updateRolePermissionsBody: MaybeRef<UpdateRolePermissionsBody>,
 ) => {
      id = unref(id);
updateRolePermissionsBody = unref(updateRolePermissionsBody);
      
      return customInstance<UpdateRolePermissions200>(
      {url: `/roles/${id}/permissions`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateRolePermissionsBody
    },
      );
    }
  


export const getUpdateRolePermissionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRolePermissions>>, TError,{id: number;data: UpdateRolePermissionsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateRolePermissions>>, TError,{id: number;data: UpdateRolePermissionsBody}, TContext> => {

const mutationKey = ['updateRolePermissions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRolePermissions>>, {id: number;data: UpdateRolePermissionsBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateRolePermissions(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateRolePermissionsMutationResult = NonNullable<Awaited<ReturnType<typeof updateRolePermissions>>>
    export type UpdateRolePermissionsMutationBody = UpdateRolePermissionsBody
    export type UpdateRolePermissionsMutationError = unknown

    /**
 * @summary 分配角色权限
 */
export const useUpdateRolePermissions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRolePermissions>>, TError,{id: number;data: UpdateRolePermissionsBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateRolePermissions>>,
        TError,
        {id: number;data: UpdateRolePermissionsBody},
        TContext
      > => {

      const mutationOptions = getUpdateRolePermissionsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 更新指定角色的菜单列表。
 * @summary 分配角色菜单
 */
export const updateRoleMenus = (
    id: MaybeRef<number>,
    updateRoleMenusBody: MaybeRef<UpdateRoleMenusBody>,
 ) => {
      id = unref(id);
updateRoleMenusBody = unref(updateRoleMenusBody);
      
      return customInstance<UpdateRoleMenus200>(
      {url: `/roles/${id}/menus`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateRoleMenusBody
    },
      );
    }
  


export const getUpdateRoleMenusMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRoleMenus>>, TError,{id: number;data: UpdateRoleMenusBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateRoleMenus>>, TError,{id: number;data: UpdateRoleMenusBody}, TContext> => {

const mutationKey = ['updateRoleMenus'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateRoleMenus>>, {id: number;data: UpdateRoleMenusBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateRoleMenus(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateRoleMenusMutationResult = NonNullable<Awaited<ReturnType<typeof updateRoleMenus>>>
    export type UpdateRoleMenusMutationBody = UpdateRoleMenusBody
    export type UpdateRoleMenusMutationError = unknown

    /**
 * @summary 分配角色菜单
 */
export const useUpdateRoleMenus = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateRoleMenus>>, TError,{id: number;data: UpdateRoleMenusBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateRoleMenus>>,
        TError,
        {id: number;data: UpdateRoleMenusBody},
        TContext
      > => {

      const mutationOptions = getUpdateRoleMenusMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 获取系统中所有菜单的列表。
 * @summary 获取所有菜单列表
 */
export const getAllMenus = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetAllMenus200>(
      {url: `/menus`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllMenusQueryKey = () => {
    return [
    'menus'
    ] as const;
    }

    
export const getGetAllMenusQueryOptions = <TData = Awaited<ReturnType<typeof getAllMenus>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMenus>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  getGetAllMenusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllMenus>>> = ({ signal }) => getAllMenus(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllMenus>>, TError, TData> 
}

export type GetAllMenusQueryResult = NonNullable<Awaited<ReturnType<typeof getAllMenus>>>
export type GetAllMenusQueryError = unknown


/**
 * @summary 获取所有菜单列表
 */

export function useGetAllMenus<TData = Awaited<ReturnType<typeof getAllMenus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMenus>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllMenusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * 创建一个新的菜单项。
 * @summary 新增菜单
 */
export const createMenu = (
    createMenuBody: MaybeRef<CreateMenuBody>,
 signal?: AbortSignal
) => {
      createMenuBody = unref(createMenuBody);
      
      return customInstance<CreateMenu201>(
      {url: `/menus`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createMenuBody, signal
    },
      );
    }
  


export const getCreateMenuMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMenu>>, TError,{data: CreateMenuBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createMenu>>, TError,{data: CreateMenuBody}, TContext> => {

const mutationKey = ['createMenu'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMenu>>, {data: CreateMenuBody}> = (props) => {
          const {data} = props ?? {};

          return  createMenu(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMenuMutationResult = NonNullable<Awaited<ReturnType<typeof createMenu>>>
    export type CreateMenuMutationBody = CreateMenuBody
    export type CreateMenuMutationError = Error

    /**
 * @summary 新增菜单
 */
export const useCreateMenu = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMenu>>, TError,{data: CreateMenuBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createMenu>>,
        TError,
        {data: CreateMenuBody},
        TContext
      > => {

      const mutationOptions = getCreateMenuMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 根据ID获取菜单详情。
 * @summary 获取菜单详情
 */
export const getMenuById = (
    id: MaybeRef<number>,
 signal?: AbortSignal
) => {
      id = unref(id);
      
      return customInstance<GetMenuById200>(
      {url: `/menus/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetMenuByIdQueryKey = (id?: MaybeRef<number>,) => {
    return [
    'menus',id
    ] as const;
    }

    
export const getGetMenuByIdQueryOptions = <TData = Awaited<ReturnType<typeof getMenuById>>, TError = Error>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMenuById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  getGetMenuByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMenuById>>> = ({ signal }) => getMenuById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMenuById>>, TError, TData> 
}

export type GetMenuByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMenuById>>>
export type GetMenuByIdQueryError = Error


/**
 * @summary 获取菜单详情
 */

export function useGetMenuById<TData = Awaited<ReturnType<typeof getMenuById>>, TError = Error>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMenuById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMenuByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * 更新现有菜单信息。
 * @summary 更新菜单
 */
export const updateMenu = (
    id: MaybeRef<number>,
    updateMenuBody: MaybeRef<UpdateMenuBody>,
 ) => {
      id = unref(id);
updateMenuBody = unref(updateMenuBody);
      
      return customInstance<UpdateMenu200>(
      {url: `/menus/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateMenuBody
    },
      );
    }
  


export const getUpdateMenuMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMenu>>, TError,{id: number;data: UpdateMenuBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateMenu>>, TError,{id: number;data: UpdateMenuBody}, TContext> => {

const mutationKey = ['updateMenu'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMenu>>, {id: number;data: UpdateMenuBody}> = (props) => {
          const {id,data} = props ?? {};

          return  updateMenu(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMenuMutationResult = NonNullable<Awaited<ReturnType<typeof updateMenu>>>
    export type UpdateMenuMutationBody = UpdateMenuBody
    export type UpdateMenuMutationError = Error

    /**
 * @summary 更新菜单
 */
export const useUpdateMenu = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMenu>>, TError,{id: number;data: UpdateMenuBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateMenu>>,
        TError,
        {id: number;data: UpdateMenuBody},
        TContext
      > => {

      const mutationOptions = getUpdateMenuMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 删除指定菜单。注意：如果存在子菜单则无法删除。
 * @summary 删除菜单
 */
export const deleteMenu = (
    id: MaybeRef<number>,
 ) => {
      id = unref(id);
      
      return customInstance<DeleteMenu200>(
      {url: `/menus/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteMenuMutationOptions = <TError = Error | Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMenu>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteMenu>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteMenu'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMenu>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteMenu(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteMenuMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMenu>>>
    
    export type DeleteMenuMutationError = Error | Error

    /**
 * @summary 删除菜单
 */
export const useDeleteMenu = <TError = Error | Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMenu>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteMenu>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteMenuMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 获取所有商品的列表。
 * @summary 获取商品列表
 */
export const getAllProducts = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetAllProducts200>(
      {url: `/products`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllProductsQueryKey = () => {
    return [
    'products'
    ] as const;
    }

    
export const getGetAllProductsQueryOptions = <TData = Awaited<ReturnType<typeof getAllProducts>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  getGetAllProductsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllProducts>>> = ({ signal }) => getAllProducts(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData> 
}

export type GetAllProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllProducts>>>
export type GetAllProductsQueryError = unknown


/**
 * @summary 获取商品列表
 */

export function useGetAllProducts<TData = Awaited<ReturnType<typeof getAllProducts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllProductsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * 创建新的商品记录。
 * @summary 创建商品
 */
export const createProduct = (
    product: MaybeRef<Product>,
 signal?: AbortSignal
) => {
      product = unref(product);
      
      return customInstance<CreateProduct201>(
      {url: `/products`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: product, signal
    },
      );
    }
  


export const getCreateProductMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: Product}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: Product}, TContext> => {

const mutationKey = ['createProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProduct>>, {data: Product}> = (props) => {
          const {data} = props ?? {};

          return  createProduct(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProductMutationResult = NonNullable<Awaited<ReturnType<typeof createProduct>>>
    export type CreateProductMutationBody = Product
    export type CreateProductMutationError = Error

    /**
 * @summary 创建商品
 */
export const useCreateProduct = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProduct>>, TError,{data: Product}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof createProduct>>,
        TError,
        {data: Product},
        TContext
      > => {

      const mutationOptions = getCreateProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 根据ID获取商品详情。
 * @summary 获取商品详情
 */
export const getProductById = (
    id: MaybeRef<number>,
 signal?: AbortSignal
) => {
      id = unref(id);
      
      return customInstance<GetProductById200>(
      {url: `/products/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetProductByIdQueryKey = (id?: MaybeRef<number>,) => {
    return [
    'products',id
    ] as const;
    }

    
export const getGetProductByIdQueryOptions = <TData = Awaited<ReturnType<typeof getProductById>>, TError = Error>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  getGetProductByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProductById>>> = ({ signal }) => getProductById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData> 
}

export type GetProductByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getProductById>>>
export type GetProductByIdQueryError = Error


/**
 * @summary 获取商品详情
 */

export function useGetProductById<TData = Awaited<ReturnType<typeof getProductById>>, TError = Error>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProductById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}




/**
 * 更新现有商品信息。
 * @summary 更新商品
 */
export const updateProduct = (
    id: MaybeRef<number>,
    product: MaybeRef<Product>,
 ) => {
      id = unref(id);
product = unref(product);
      
      return customInstance<UpdateProduct200>(
      {url: `/products/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: product
    },
      );
    }
  


export const getUpdateProductMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: number;data: Product}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: number;data: Product}, TContext> => {

const mutationKey = ['updateProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProduct>>, {id: number;data: Product}> = (props) => {
          const {id,data} = props ?? {};

          return  updateProduct(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProductMutationResult = NonNullable<Awaited<ReturnType<typeof updateProduct>>>
    export type UpdateProductMutationBody = Product
    export type UpdateProductMutationError = Error

    /**
 * @summary 更新商品
 */
export const useUpdateProduct = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: number;data: Product}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateProduct>>,
        TError,
        {id: number;data: Product},
        TContext
      > => {

      const mutationOptions = getUpdateProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 删除指定商品。
 * @summary 删除商品
 */
export const deleteProduct = (
    id: MaybeRef<number>,
 ) => {
      id = unref(id);
      
      return customInstance<DeleteProduct200>(
      {url: `/products/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteProductMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteProduct'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProduct>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteProduct(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProductMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProduct>>>
    
    export type DeleteProductMutationError = Error

    /**
 * @summary 删除商品
 */
export const useDeleteProduct = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof deleteProduct>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 手动触发权限变更事件，用于测试或强制刷新客户端权限状态。
 * @summary 触发权限变更通知
 */
export const triggerPermissionChange = (
    triggerPermissionChangeBody: MaybeRef<TriggerPermissionChangeBody>,
 signal?: AbortSignal
) => {
      triggerPermissionChangeBody = unref(triggerPermissionChangeBody);
      
      return customInstance<TriggerPermissionChange200>(
      {url: `/permissions/change`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: triggerPermissionChangeBody, signal
    },
      );
    }
  


export const getTriggerPermissionChangeMutationOptions = <TError = Error | Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerPermissionChange>>, TError,{data: TriggerPermissionChangeBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof triggerPermissionChange>>, TError,{data: TriggerPermissionChangeBody}, TContext> => {

const mutationKey = ['triggerPermissionChange'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerPermissionChange>>, {data: TriggerPermissionChangeBody}> = (props) => {
          const {data} = props ?? {};

          return  triggerPermissionChange(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TriggerPermissionChangeMutationResult = NonNullable<Awaited<ReturnType<typeof triggerPermissionChange>>>
    export type TriggerPermissionChangeMutationBody = TriggerPermissionChangeBody
    export type TriggerPermissionChangeMutationError = Error | Error

    /**
 * @summary 触发权限变更通知
 */
export const useTriggerPermissionChange = <TError = Error | Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerPermissionChange>>, TError,{data: TriggerPermissionChangeBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof triggerPermissionChange>>,
        TError,
        {data: TriggerPermissionChangeBody},
        TContext
      > => {

      const mutationOptions = getTriggerPermissionChangeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
